
- hosts: zabbix-server
  become: yes
  roles:
     - { role: ansible-role-mysql }
     - { role: ansible-zabbix-server, database_type: mysql, database_type_long: mysql, server_dbport: 3306 }
     - { role: ansible-role-apache }
     - { role: ansible-zabbix-web, zabbix_url: zabbix.example.com, database_type: mysql, database_type_long: mysql, server_dbport: 3306}

- hosts: zabbix-agent
  become: yes
  roles:
     - { role: ansible-zabbix-agent }
