---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: requirements.yml

driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: zabbix-server-mysql-centos
    image: milcom/centos7-systemd
    privileged: True
    groups:
      - mysql
  - name: zabbix-server-pgsql-centos
    image: milcom/centos7-systemd
    privileged: True
    groups:
      - postgresql
  - name: zabbix-server-mysql-debian
    image: maint/debian-systemd
    privileged: True
    groups:
      - mysql
  - name: zabbix-server-pgsql-debian
    image: maint/debian-systemd
    privileged: True
    groups:
      - postgresql
  - name: zabbix-server-mysql-ubuntu
    image: solita/ubuntu-systemd:latest
    privileged: True
    command: /sbin/init
    groups:
      - mysql
  - name: zabbix-server-pgsql-ubuntu
    image: solita/ubuntu-systemd:latest
    privileged: True
    command: /sbin/init
    groups:
      - postgresql

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      mysql:
        database_type: mysql
        database_type_long: mysql
        server_dbport: 3306
      postgresql:
        database_type: pgsql
        database_type_long: postgresql

scenario:
  name: default
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge

verifier:
  name: testinfra
  lint:
    name: flake8
